# Generated by Django 3.0.5 on 2020-04-26 13:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200425_2259'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recipe',
            managers=[
                ('recipe_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
